### ISSUE TITLE
PHP 5 compatibility

### ISSUE THREAD

**Issue by gharlan** [dshafik/php7-mysql-shim#10]
From README:

> You may safely include the file in a PHP 5.x project, it will do nothing.

This is only true for PHP 5.6. With PHP < 5.6 you will get a parse error because of [`T_ELLIPSIS` usage](https://github.com/dshafik/php7-mysql-shim/blob/36faf77db440bce329ffe214ffd923723e8d5f23/lib/mysql.php#L538-L606) and in php < 5.3 because of namespaces.

**Comment by philip** [comment]
Pull request #22 addresses this issue.
