### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by str** [dshafik/php7-mysql-shim#102]
Now that PHP 8.2 is released I was able to test it in a legacy project I have where we use this library, but I found the first issue:

Creation of dynamic property mysqli::$hash is deprecated. Code: 8192 @ vendor/dshafik/php7-mysql-shim/lib/mysql.php +88

![image](https://user-images.githubusercontent.com/123817/206556808-93d4d69e-86ae-40fd-a51a-2928bb06161e.png)

**Comment by dshafik** [comment]
This can't be fixed as this is an internal class, which means I cannot add the annotation to allow dynamic property creation.

You really shouldn't be relying on this library at this point. ext/mysql has been gone for **7 years**, move to mysqli already. Use rector to migrate and stop using this please.
