### ISSUE TITLE
PHP 8.2: Deprecated: Creation of dynamic property mysqli::$hash is deprecated

### ISSUE THREAD

**Issue by marcovtwout** [dshafik/php7-mysql-shim#109]
Using this extension on PHP 8.2 generates the following deprecation error:

```Deprecated: Creation of dynamic property mysqli::$hash is deprecated in (..) mysql.php on line 88```

Explanation/solutions: https://php.watch/versions/8.2/dynamic-properties-deprecated

**Comment by dshafik** [comment]
This can't be fixed without awful error suppression. I suggest using rector to properly migrate to mysqli.
