### ISSUE TITLE
Error fatal on line 49

### ISSUE THREAD

**Issue by nitroxido** [dshafik/php7-mysql-shim#19]
When including this library on older versions of PHP (5.3.29), there is an error in line 49:

```
            \Dshafik\MySQL::$connections[$hash] = ['refcount' => 1, 'conn' => $conn];
```

The "[" to create an array is not allowed in this version. If you change it to the right "array(" such as:

```
            \Dshafik\MySQL::$connections[$hash] = array('refcount' => 1, 'conn' => $conn);
```

Everything work as intended (i.e., the code does nothing).

You must also make the same change in lines 77, 337, 628, 721 - 734, 736 and 748-781.

**Comment by staabm** [comment]
The lib doesnt support 5.3 right now

**Comment by dshafik** [comment]
This library is for 5.6+ as stated in the README. I will amend the composer.json to reflect this.

Thanks for taking the time to report this issue.
