### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by ygoe** [dshafik/php7-mysql-shim#20]
This is in the error log for PHP 5.5:

PHP Parse error: syntax error, unexpected '.', expecting '&​' or variable (T_VARIABLE) in /​var/​www/​.../​mysql.php on line 553

I've also seen other errors like "memory exceeded" on my local environment (PHP 7 XAMPP). Looks like I need to replace those mysql_ to mysqli_ calls myself. Need it working tomorrow.

**Comment by staabm** [comment]
The lib requires php 5.6

https://github.com/dshafik/php7-mysql-shim/blob/master/composer.json#L13

**Comment by ygoe** [comment]
Oh. Maybe this should be noted in the readme. 5.5 to 7.0 is the latest Ubuntu LTS transition and might not be that uncommon. I've fixed my code manually now.

**Comment by staabm** [comment]
Actually It is noted in the readme

**Comment by ygoe** [comment]
Are you referring to this?

> You may safely include the file in a PHP 5.6 project, it will do nothing.

I interpret this as "You may safely include the file in a PHP ≤ 5.6 (i. e. < 7.0) project", including 5.5. The readme does not say anywhere that 5.6 is required.

**Comment by staabm** [comment]
Oh, you are right. Its not explicitly mentioned.

Since mysql_* was dropped with php7 the only versions this shim actually has a effect is 7.0+. The compat with 5.6 is a bonus so you dont need version checks in your code.

**Comment by philip** [comment]
Pull request #22 addresses this issue.
