### ISSUE TITLE
mysql_db_name()'s optional third parameter

### ISSUE THREAD

**Issue by philip** [dshafik/php7-mysql-shim#23]
The PHP manual defines [mysql_db_name()](http://php.net/manual/en/function.mysql-db-name.php) as:

> string mysql_db_name ( resource $result , int $row [, mixed $field = NULL ] )

The php7-mysql-shim library does [not include](https://github.com/dshafik/php7-mysql-shim/blob/master/lib/mysql.php#L525) the third optional parameter. Unfortunately [lxr](http://lxr.php.net/xref/PHP_5_6/ext/mysql/php_mysql.c#319) is down now as otherwise I'd dig deeper now, but since the mysql_db_name() definition uses mysql_result() this might be slightly complicated. Or, maybe 'Database' could safely be replaced with $field [there](https://github.com/dshafik/php7-mysql-shim/blob/master/lib/mysql.php#L534). Or, it might be a documentation bug in the PHP manual, I'm not sure yet.

Related: the mysql_dbname alias.

**Comment by dshafik** [comment]
You're quite right, this was missed - `mysql_db_name()` and `mysql_dbname()` are both aliases to `mysql_result()`, which means they take the same third argument (which is documented for that function), and per the source, defaults to `0`.
