### ISSUE TITLE
Please move the deprecation notice, it makes builds fail.

### ISSUE THREAD

**Issue by NoMan2000** [dshafik/php7-mysql-shim#24]
Triggering the error makes development builds fail.  If you must trigger an error, you are triggering this error not because someone is actually *using* the deprecated extension, but because they are *loading* in your polyfill.  

As stated:  `This library attempts to create a drop-in replacement for ext/mysql on PHP 7 using mysqli.`

But throwing an error is not what happens if you install the mysql extension from PECL.

Worse, this triggers an error when someone isn't doing anything wrong.  If you must include this error, then move it to the connect section so it doesn't throw the error until after the person has attempted to use the plugin.

        trigger_error(
            "php7-mysql-shim: The mysql extension is deprecated "
            . "and was removed in the PHP 7.0: use mysqli or PDO instead.",
            E_USER_DEPRECATED
        );

**Comment by dshafik** [comment]
Can you elaborate on builds failing? Yours? All of this projects builds pass (although the deprecation notice is shown in the output).

I wasn't entirely happy about adding this, I initially added it to every function but that completely breaks all the tests (converted to exception by PHPUnit and that breaks the test).

Just looking for more insight before I remove it.

**Comment by NoMan2000** [comment]
I think it should only be added to the mysql_connect function.  There's no point throwing an error every time a user uses a deprecated function, I think once per connection is enough.

I checked my commit against the PHPUnit tests and it worked.  It's going through your automated tests right now.  

The error it throws in my code base is a custom one because I convert all errors to exceptions in my code.  It reads as follows:

```
PHP Deprecated:  php7-mysql-shim: The mysql extension is deprecated and was removed in the PHP 7.0: use mysqli or PDO instead. in /Users/michaelsoileau/Sites/cellcontrolDocs/vendor/dshafik/php7-mysql-shim/lib/mysql.php on line 31
```

I don't like having it thrown on the file include mainly.  If it's at least on a function, then you can use a try / catch `Throwable` on the code.  But if it's on an include, then there's no way for a user to handle the error.

**Comment by dshafik** [comment]
@NoMan2000 I'm inclined to just remove it entirely, as you see in your PR (#25) it causes all tests to fail due to the way PHPUnit handles things.

**Comment by NoMan2000** [comment]
That's cool too.  I just wasn't sure if you wanted it to remain for a reason.  If not, feel free to remove it.  👍

**Comment by dshafik** [comment]
Done in f5b1bc9. Thanks!
