### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by sonnysavage** [dshafik/php7-mysql-shim#27]
I tried to include this project in a PHP 5.3.10 project that I'm migrating to PHP 7.0. Your documentation states, "[You may safely include the file in a PHP 5.3.6+ project...](https://github.com/dshafik/php7-mysql-shim#usage)".

I'm getting this parse error:  
`[10-Feb-2017 18:25:01 UTC] PHP Parse error:  syntax error, unexpected '[' in /[SNIP]/vendor/dshafik/php7-mysql-shim/lib/mysql.php on line 49`

**Comment by staabm** [comment]
Which version of this lib do you use?

**Comment by sonnysavage** [comment]
My Composer config: `"dshafik/php7-mysql-shim": "*"`

I assume that gets me the latest. Am I incorrect on that?

**Comment by staabm** [comment]
You need to use one of the 1.0.0 betas for 5.3.6 support.

With the * constraint you will per default get the latest stable which is 0.2

**Comment by staabm** [comment]
To get nonstable releases you need to define minimum-stability or use a different version constraint.

Using * is not a good idea at all though.. you should use more explicit version constraints

**Comment by sonnysavage** [comment]
Thank you! I've changed my configuration to: `"dshafik/php7-mysql-shim": "1.*@beta"`

I'm a Composer newb, so I had to look it all up.

**Comment by staabm** [comment]
Great. If your problem is solved please close this issue then.

**Comment by thinsoldier** [comment]
> Thank you! I've changed my configuration to: `"dshafik/php7-mysql-shim": "1.*@beta"`

This should really be mentioned in the Readme right next to where it says it works in 5.6.3
