### ISSUE TITLE
Connection failure reason is omitted

### ISSUE THREAD

**Issue by kiler129** [dshafik/php7-mysql-shim#30]
Hi,

I discovered small annoyance while using this shim. In case of connection failure message *"A link to the server could not be established"* is displayed, which is not very informative. 

I think `Dshafik\MySQL::getConnection()` will benefit from adding extra information about the error (provided by `mysqli_connect_error()`). Do you have anything against that @dshafik? If not I can make a PR.

**Comment by dshafik** [comment]
The only issue I have against it is that it breaks the authenticity of the shim, _however_, people shouldn't rely on error messages, so I think this one might be OK.

Perhaps: `"A link to the server could not be established (" .mysqli_connect_error(). ")"`

**Comment by dshafik** [comment]
@kiler129 would this be acceptable?
