### ISSUE TITLE
mysql_tablename is wrong

### ISSUE THREAD

**Issue by vaso123** [dshafik/php7-mysql-shim#36]
Hi!
Sadly, mysql_tablename is not good.

The problem is that your query is:  SHOW TABLES FROM `%s`

The column name is Tables_in_[databasename], while you want to get 'Table'

**Comment by vaso123** [comment]
I've just created a fix here: https://github.com/vaso123/php7-mysql-shim

**Comment by staabm** [comment]
Willing to provide a PR? At best with a unit test

**Comment by vaso123** [comment]
Sorry, not time for it.

**Comment by rokclimb15** [comment]
Just reviewing these bugs to see if I can help. It's unclear why this is a problem. The existing SQL is valid and should work. @vaso123 can you explain?
