### ISSUE TITLE
MySQL is read-only

### ISSUE THREAD

**Issue by nkkollaw** [dshafik/php7-mysql-shim#37]
Hi!

I'm trying to fix this project from 2007. Is it possible that the DB works in read-only mode (ex., it appears to work but doesn't save any data?)

Thanks!

**Comment by staabm** [comment]
we used this project successfully in read/write scenarios.

its likely a problem on your end, maybe a permission issue?
any error messages?

**Comment by nkkollaw** [comment]
I can confirm that I don't have any permission issues. I tried connecting as root and nothing changed. I'm also not getting any error messages.

I'm closing this as I can't seem to be able to understand the problem enough to report a possible bug with my particular configuration.

Thanks, though--and awesome project!
