### ISSUE TITLE
Object returned in mysqli_fetch_field is not the same as the one mysql_fetch_field used to return

### ISSUE THREAD

**Issue by GerMalaz** [dshafik/php7-mysql-shim#38]
From http://php.net/manual/en/function.mysql-fetch-field.php

 Returns an object containing field information. The properties of the object are:

    name - column name
    table - name of the table the column belongs to, which is the alias name if one is defined
    max_length - maximum length of the column
    not_null - 1 if the column cannot be NULL
    primary_key - 1 if the column is a primary key
    unique_key - 1 if the column is a unique key
    multiple_key - 1 if the column is a non-unique key
    numeric - 1 if the column is numeric
    blob - 1 if the column is a BLOB
    type - the type of the column
    unsigned - 1 if the column is unsigned
    zerofill - 1 if the column is zero-filled

mysqli_fetch_field returned object has name, table and max_length properties but the rest is encoded in the flags property.

Attached a patch which creates those properties based on the flags property.

[shim_fetch_field.patch.txt](https://github.com/dshafik/php7-mysql-shim/files/1729508/shim_fetch_field.patch.txt)

**Comment by dshafik** [comment]
@GerMalaz I know this has been sitting out here for a good long while; any chance you can create a PR with a unit test? If not, I'll get to it at some point!

**Comment by dshafik** [comment]
Fixed with 81720edfa0a801efdcb6a8b19c014b9a7bb437f9
