### ISSUE TITLE
Resolve PHP 7.4 Deprecations

### ISSUE THREAD

**Issue by siemendev** [dshafik/php7-mysql-shim#46]
Hi there, hope I'm reporting this correct here.

With PHP@7.4 composer tells me this:
Deprecation Notice: Array and string offset access syntax with curly braces is deprecated in /vendor/bbrala/php7-mysql-shim/lib/mysql.php:58

Looks like there is a deprecation that should be solved?

**Comment by dshafik** [comment]
Fixed by #47. Thanks for reporting this issue! 🥇

**Comment by siemendev** [comment]
@dshafik is there any plan on releasing a beta3 or something so the composer update will fetch these changes?

**Comment by dshafik** [comment]
@siemendev tagged! :)
