### ISSUE TITLE
PHP 8.0  Array and string offset access syntax with curly braces is no longer supported

### ISSUE THREAD

**Issue by str** [dshafik/php7-mysql-shim#62]
Using this lib in a PHP 8.0 projectreturns the following error message:

`( ! ) Fatal error: Array and string offset access syntax with curly braces is no longer supported in [...]/vendor/dshafik/php7-mysql-shim/lib/mysql.php on line 35`

**Comment by dshafik** [comment]
@str I believe you are using an old version of the library, can you please try updating to the last one and check again?

**Comment by str** [comment]
I'm using 0.2.0, as that's what composer installs.  I see the line with the issue:

```php
            if ($hostname{1} != ':' && isset(\Dshafik\MySQL::$connections[$hash])) {
```

It should be 

```php
            if ($hostname[1] != ':' && isset(\Dshafik\MySQL::$connections[$hash])) {
```

**Comment by str** [comment]
I see that if I force the 1.0.0beta4 in composer.json, it works.
