### ISSUE TITLE
mysqli_fetch_field loop in mysql_result won't reset it's pointer back to zero

### ISSUE THREAD

**Issue by jorijn** [dshafik/php7-mysql-shim#7]
When searching for multiple (named) columns, the pointer for mysql_fetch_field doesn't get set back to zero, every request to mysql_result(..., ..., ...) therefor will fail due to being unable to find the proper result item.

Example:

```
$res = mysql_query('SELECT * FROM tbl1, tbl2');

$val1 = mysql_result($res, 0, 'tbl1.col1');
$val2 = mysql_result($res, 0, 'tbl1.col2');
$val3 = mysql_result($res, 0, 'tbl1.col3');
```

Solution:

Add `mysqli_field_seek($result, 0);` just above the `while()` loop on line 238.

**Comment by dshafik** [comment]
@Jorijn good catch, and your suggested fix is exactly the right one, thanks!
